version: 3

dotenv:
  - ".env"

tasks:
  default:
    desc: List all tasks
    aliases:
      - list
    cmd: task -l

  run:server:
    desc: Start Go server
    dir: ./api
    cmd: HOST={{.HOST}} go run ./cmd/server/main.go
  run:native:
    desc: Start React Native server
    dir: ./native
    cmd: pnpm run start

  gen:proto:
    desc: Generate gRPC stub code
    dir: ./
    cmd: buf generate proto
