version: "2"

linters:
  default: fast
  enable:
    - errcheck
  disable:
    - depguard
  settings:
    misspell:
      locale: US
      extra-words:
        - typo: "iff"
          correction: "if"

formatters:
  enable:
    - gofmt
    - goimports

run:
  tests: false
  timeout: 1m
